# Generated by Django 5.0.6 on 2024-06-25 14:07

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('suk_game', models.IntegerField(primary_key=True, serialize=False)),
                ('dtm_game', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GameDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssk_play', models.IntegerField()),
                ('board_state', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=8), size=8)),
                ('suk_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('suk_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
            ],
        ),
    ]
