# Generated by Django 5.0.6 on 2024-07-09 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('player', '0004_rename_email_player_player_player_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_activee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='suk_player_1',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player_1', to='player.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='suk_player_2',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player_2', to='player.player'),
            preserve_default=False,
        ),
    ]
