# Generated by Django 5.0.6 on 2024-07-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_game_activee_game_suk_player_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_activee',
            new_name='game_active',
        ),
    ]
