# Generated by Django 5.0.6 on 2024-07-09 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_game_activee_game_game_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='dtm_game',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
