# Generated by Django 5.0.6 on 2024-06-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('suk_player', models.IntegerField(primary_key=True, serialize=False)),
                ('nm_player', models.CharField()),
                ('email_player', models.CharField()),
            ],
        ),
    ]
