# Generated by Django 5.0.6 on 2024-07-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_player_image_player_total_number_games_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='email_player',
            new_name='player_email',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='image',
            new_name='player_image',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='nm_player',
            new_name='username',
        ),
        migrations.AddField(
            model_name='player',
            name='player_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='player_country',
            field=models.CharField(default='No country defined'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_name',
            field=models.CharField(default='No name defined'),
        ),
    ]
